silverhand-io/configs

packages/eslint-config/index.js

Some how eslint-config-xo-typescript disabled this [rule](https://github.com/xojs/eslint-config-xo-typescript/blob/main/index.js#L446) by default, need to enable it 
[rule details](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-non-null-assertion.md)
@gao-sun @wangsijie cc: @IceHe @xiaoyijun @darcyYe

feat(eslint-typescript): enable no-non-null-assertion rule

---

packages/eslint-config/index.js

In monorepo, when lacking of `tsconfig.js` in repo's root, can see error `Parsing error: Cannot read file '.../tsconfig.json'`
https://stackoverflow.com/a/69290802/14995215

fix: find tsconfig

---

packages/eslint-config/index.js

Per [slack discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1639981870158400), globally disabling eslint rules in a file is not recommended and `eslint-disable` switch should work with following `eslint-enable`.
Tested the configuration locally in repo logto/js.
The globally `eslint-disable` comments were marked as errors and this error can be fixed as long as corresponding `eslint-enable` rules were added in the file.
This rule can also be fixed by breaking the global config into local configs.

chore: fix eslint-disable rule configuration

---

packages/eslint-config/index.js

Use `@typescript-eslint/padding-line-between-statements` instead of the base eslint rule.
Now it will also add new line before typescript interfaces and types.

fix(eslint-config): fix padding line between statements rule

---

packages/eslint-config/index.js

https://typescript-eslint-armano.netlify.app/rules/no-unnecessary-condition/
Avoid having unnecessary optional check/chaining in typescript

feat(eslint-config): no-unnecessary-condition rule

---

.gitignore
packages/eslint-config/package.json
pnpm-lock.yaml

- **fix(eslint-config): fix member-ordering rule via updating eslint-config-xo-typescript dependency to 0.50.0**
- chore(eslint-config): update eslint-config-xo dependency to 0.40.0
- chore: add .idea to .gitignore
Problem:
Solution:
- Update the dependencies 
- eslint-config-xo-typescript to the latest version 0.50.0
- including the patch: "[Improve ordering in @typescript-eslint/member-ordering](https://github.com/xojs/eslint-config-xo-typescript/commit/384e3701e275dd664d74391e63954fc405427d55)" in [v0.45.0](https://github.com/xojs/eslint-config-xo-typescript/commit/384e3701e275dd664d74391e63954fc405427d55)
> Thanks to @demonzoo
References:
* https://github.com/typescript-eslint/typescript-eslint/blob/v5.6.0/packages/eslint-plugin/docs/rules/member-ordering.md
* …

fix(eslint-config): fix rule member-ordering via updating dependencies

---

packages/eslint-config/index.js
packages/eslint-config/package.json

Fix eslint by bumping typescript-eslint plugin versions and override several unnecessary rules.
Target patch version: 0.9.1

fix: bump typescript eslint plugins and disable unnecessary rules

---

packages/eslint-config-react/.stylelintrc.json

disable the rule since parcel cannot recognize the modern notation
tested in project

fix(eslint-react): use `legacy` for `color-function-notation`

---

packages/eslint-config-react/index.js

update the rule since TypeScript / VSCode won't recognize
with default rule in `xo-react`:
with this override:
in VSCode

fix(eslint-react): update `react/jsx-curly-brace-presence`

---

packages/eslint-config-react/index.js

when using `.tsx`:
- turn off `react/button-has-type`
- don't check args in `unicorn/no-useless-undefined`
since they are conflict with TypeScript
N/A

fix(eslint-react): update config

---

packages/eslint-config-react/index.js

Update eslint-react to allow `!!` in React tsx files.
[LOG-2052](https://linear.app/silverhand/issue/LOG-2052/allow-value-type-conversion-and-ref-abbreviation-in-react-eslint)

feat(eslint-react): allow double exclamation marks in react tsx

---

packages/eslint-config-react/replacements.js

Update eslint-react to allow `ref` abbreviation in React project
[LOG-2052](https://linear.app/silverhand/issue/LOG-2052/allow-value-type-conversion-and-ref-abbreviation-in-react-eslint)

feat(react-eslint): allow 'ref' abbreviation in React

---

packages/eslint-config-react/package.json
pnpm-lock.yaml

update direct dependency `eslint-plugin-react` to `^7.29.0` since `propElementValues` added in https://github.com/jsx-eslint/eslint-plugin-react/releases/tag/v7.29.0
CI

fix(react-config): update dependency

---

packages/eslint-config/package.json

Remove typescript from eslint-config peer dependencies list, as it might be used in a non-typescript project like `react-sample`.

fix(eslint-config): remove typescript from eslint-config peer dependencies

---

packages/eslint-config-react/index.js

Disable `node/file-extension-in-import` rule for the following file extensions in `eslint-config-react`
* js
* jsx
* ts
* tsx

fix(eslint-config-react): disable 'node/file-extension-in-import' rule

---

packages/eslint-config-react/.stylelintrc.json

ignore `global` in stylelint `selector-pseudo-class-no-unknown` rule to prevent false positive. extracted from `core/ui`.
N/A

fix(config-react): ignore `global` for pseudo class

---

packages/eslint-config/package.json
pnpm-lock.yaml

the new version will cause `ESLint couldn't find the plugin`, see [workflow run](https://github.com/silverhand-io/configs/actions/runs/3239774704/jobs/5309570606)
CI

chore: fix version of eslint-plugin-sql

---

package.json
packages/eslint-config-react/package.json
packages/jest-config/package.json
packages/ts-config-react/package.json
packages/ts-config/package.json
pnpm-lock.yaml

- revert #76 since it has lockfile issue with pnpm
- add `version` command
- pnpm build + CI
- `pnpm lerna version --no-push` works as expected

chore: revert lerna version bump

---

packages/jest-config/jest.config.ts

jest v29 has some trouble with ESM in node_modues. will cause `SyntaxError: Cannot use import statement outside a module` again if not properly configured. this PR resolves the issue.
also, only necessary files are transformed by ts-jest:
js files in other modules are not being transformed, e.g., i18next

fix(jest): update config to work with jest v29

---

.changeset/config.json
packages/eslint-config-react/package.json
packages/jest-config/package.json
packages/ts-config-react/package.json
packages/ts-config/package.json
pnpm-lock.yaml

- use `workspace:` protocol to ack changesets for dependencies
- properly link packages for version bumping
execute `changeset version` -> both `eslint-config` + `eslint-config-react` bump to `1.3.0`

chore: update version bump configs

---

.github/workflows/publish.yml
.github/workflows/release.yml
package.json

- decouple tagging and npm publishing, now it's like:
- merge versioning PR -> tag, create GitHub release -> publish to NPM
- caveat: `pnpm -r publish` won't fail. track in:
- pnpm/pnpm#5528
after merging, try a force prerelease publish

ci: update publish flow

---

.changeset/stupid-falcons-walk.md
packages/eslint-config/index.js

This rule brings more trouble than it solves. We have a lot of dynamic enum checks

refactor: turn off `@typescript-eslint/no-unsafe-enum-comparison`
