silverhand-io/configs

packages/eslint-config/index.js, packages/eslint-config/package.json, pnpm-lock.yaml
Add [eslint-plugin-sql](https://github.com/gajus/eslint-plugin-sql) and several rules.
Manually tested: I created a new repo and write some code, works fine with vscode and prettier.
Do I need to change package version in this PR? @gao-sun
=> feat(eslint-config): eslint-plugin-sql

packages/eslint-config/index.js
chore: update lint-related configurations
https://linear.app/silverhand/issue/LOG-534/update-lint-related-configurations-silverhandconfigs
Test of the configuration can be found:
https://github.com/logto-io/js/pull/111
https://github.com/logto-io/logto/pull/155
=> chore: update lint-related configurations

packages/eslint-config/index.js
add id-length mimium length 2 rule
log-1116
@gao-sun
=> feat(config): add id-length rule

package.json, packages/eslint-config/package.json, pnpm-lock.yaml
compatibility work of `eslint@8`
=> chore(eslint-config): upgrade packages

pnpm-lock.yaml
=> fix(eslint-config): update `pnpm-lock.yaml`

packages/eslint-config-react/package.json, packages/eslint-config/package.json, packages/ts-config-react/package.json, packages/ts-config/package.json, pnpm-lock.yaml
- upgrade dev dependency eslint and typescript to the latest version
- loose peer dependency stylelint version
N/A
=> chore: upgrade packages

packages/eslint-config/index.js
=> feat(config): add `max-lines`

packages/eslint-config/index.js
loose `max-lines` to 400 for test files
tested in `@logto/logto`
=> refactor(config): loose `max-lines` for test files

packages/eslint-config/index.js
=> fix(config): typo

packages/eslint-config/index.js
Add complexity max 5 rule
LOG-1374
=> feat(eslint): add complexity max 5

packages/eslint-config/package.json, pnpm-lock.yaml
eslint reports error in a new project that cannot resolve `pkg-dir`
- add dependency to avoid error
- upgrade lockfile
eslint works
=> fix(config): add `pkg-dir` as dependency

packages/eslint-config-react/package.json, pnpm-lock.yaml
to enable stylelint 14
no warning while installing stylelint 14
=> chore: upgrade stylint config

packages/jest-config/jest.config.ts, packages/jest-config/package.json, packages/jest-config/tsconfig.json, pnpm-lock.yaml
add shared jest config package
=> feat: `jest-config`

packages/eslint-config-react/index.js, packages/eslint-config/index.js
Refactor file `import/extension` rules
=> refactor: file import/extension rules

packages/eslint-config/index.js
Explicit `any` is not allowed.
LOG-2140
Tried it `logto/logto`
=> feat(eslint-config): no explicit any

packages/eslint-config/index.js
it caused problems several times
tested in core
=> feat(eslint): ban `as` in non-test ts files

packages/eslint-config/index.js
allow `as const` since it's ok
tested in core
=> refactor(eslint): allow `as const`

packages/eslint-config-react/index.js
allows referrer for better stats
in website
=> refactor: allow referrer in target blank links

packages/eslint-config/index.js, packages/eslint-config/package.json, pnpm-lock.yaml
add no-unused-imports rule
N/A
=> feat(config): add no-unused-imports rule

packages/eslint-config-react/index.js, packages/eslint-config-react/package.json, pnpm-lock.yaml
Since we are gonna have SIE2.0 development. Would like to add the a11y eslint rule ahead.
test locally
=> feat(config): add a11y eslint rule

.github/workflows/main.yml, .github/workflows/publish.yml, lerna.json, package.json, pnpm-lock.yaml
remove lerna, use native `pnpm -r` to run scripts
CI
=> chore: remove lerna

.github/workflows/release.yml
=> ci: add setup node and pnpm setup

.changeset/odd-gorillas-jump.md, packages/eslint-config-react/index.js, packages/eslint-config/index.js
=> refactor: fix conflict rules and update complexity for react files

.changeset/wicked-queens-kick.md, packages/ts-config/tsconfig.base.json
update tsconfig per our new convention
/
=> chore: update tsconfig

.changeset/dull-carpets-peel.md, packages/ts-config-react/tsconfig.base.json, packages/ts-config/tsconfig.base.json
found some build error in core CI
locally ran `pnpm -r build` and `pnpm -r lint` shows no error
=> refactor: tweak tsconfig to fit dev env

.changeset/khaki-moose-peel.md, packages/ts-config/tsconfig.base.json
update tsconfig per practice
https://github.com/microsoft/TypeScript/issues/50971
finally works, see [this run](https://github.com/logto-io/logto/pull/3136/commits/e109ed9a264a24c8d588cc0c7373c68aa397a960)
=> refactor: update tsconfig

.changeset/tall-games-study.md, packages/jest-config/package.json
mistyped before
tested in logto core. works
=> fix(jest): fix package.json export

.changeset/swift-singers-matter.md, packages/eslint-config/index.js
=> fix(config): disable padding-line-between-statements rules

.changeset/stale-planes-confess.md, package.json, packages/eslint-config-react/package.json, packages/eslint-config/package.json, packages/jest-config/package.json, packages/ts-config-react/package.json, packages/ts-config/package.json, pnpm-lock.yaml
upgrade a lot of packages
tested in `core` `console` and `ui`, all good
=> chore!: upgrade packages

packages/eslint-config/replacements.js
allow the use of the abbreviation 'dev'
No need
=> feat(config): allow the use of the abbreviation 'dev'

.changeset/bright-pandas-fix.md
=> chore: add changeset

.changeset/fifty-kids-promise.md, packages/eslint-config-react/CHANGELOG.md, packages/eslint-config/CHANGELOG.md, packages/eslint-config/package.json
fix eslint peer dependency version
=> release: v4.0.1

.changeset/honest-jars-double.md
=> release: version packages

packages/eslint-config-react/package.json, packages/eslint-config/package.json, packages/ts-config-react/package.json, packages/ts-config/package.json, pnpm-lock.yaml
=> chore: upgrade eslint

packages/eslint-config/package.json, pnpm-lock.yaml
=> chore: upgrade eslint plugins
